version: '3.1'
services:
    directors_web_app:
       build:
         context: ./flask_app
         dockerfile: Dockerfile
       ports:
         - "5011:5000"
       depends_on:
         - db
    directors_rest_api:
       build:
         context: ./flask_rest
         dockerfile: Dockerfile
       ports:
         - "5010:5000"
       depends_on:
         - db
    db:
       image: mongo:3.6.4
       volumes:
         - mongodb:/data/db
    nginx:
       build:
         context: ./nginx
         dockerfile: Dockerfile
       ports:
         - "80:80"
       restart: always
       depends_on:
         - directors_web_app
         - directors_rest_api
volumes:
   mongodb:
      external: false

